@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed May 13 15:59:36 +0300 2026
REM SW Build 6403652 on Thu Mar 19 19:48:24 GMT 2026
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim ex_brightness_decrease_behav -key {Behavioral:examples:Functional:ex_brightness_decrease} -tclbatch ex_brightness_decrease.tcl -log simulate.log"
call xsim  ex_brightness_decrease_behav -key {Behavioral:examples:Functional:ex_brightness_decrease} -tclbatch ex_brightness_decrease.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
