#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 13 13:17:57 +03 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim ex_prewitt3x3_behav -key {Behavioral:examples:Functional:ex_prewitt3x3} -tclbatch ex_prewitt3x3.tcl -log simulate.log"
xsim ex_prewitt3x3_behav -key {Behavioral:examples:Functional:ex_prewitt3x3} -tclbatch ex_prewitt3x3.tcl -log simulate.log

